---
type: media_spine

media_spine:
  defaults:
    platform: 7808R3
    loopback_ipv4_pool: 169.27.195.0/25
    bgp_as: "65211.37200"
    bgp_defaults:
    # Literal bgp commands <str>
      - bgp asn notation asdot
      - timers bgp 5 15
      - neighbor default send-community
      #- maximum-paths 128
      #- no bgp default ipv4-unicast
      # - distance bgp 20 200 200
      # - graceful-restart restart-time 300
      # - graceful-restart
      #- no redistribute attached-host
    filter:
      tenants: [ blue ]
    ptp:
      source_ip: 169.27.195.33
      priority1: 20
      priority2: 102
      ttl: 8
      monitor:
        #enabled: <bool; default=True>
        threshold:
          offset_from_master: 500
          mean_path_delay: 2500
        missing_message:
                sequence_ids:
                  enabled: False
  nodes:
    - name: C160064-037B200A
      id: 1
      loopback_ipv4_address: 169.27.195.33
      mgmt_interface: Management1/1
      mgmt_ip: 10.176.143.168/27
      mgmt_gateway: 10.176.143.161

management_cvx:
  shutdown: false
  server_hosts:
  # IP or hostname.
    - 10.155.243.151
    - 10.155.243.152
    - 10.155.243.153
  # Interface name.
  source_interface: Loopback0
