---
type: media_spine

media_spine:
  defaults:
    platform: 7808R3
    loopback_ipv4_pool: 169.27.195.0/25
    bgp_as: "65010.1"
    bgp_defaults:
    # Literal bgp commands <str>
      - bgp asn notation asdot
      - no bgp default ipv4-unicast
      - timers bgp 5 15
      - distance bgp 20 200 200
      - graceful-restart restart-time 300
      - graceful-restart
      - maximum-paths 128
      - neighbor default send-community
    filter:
      tenants: [ blue ]

  nodes:
    - name: blue-spine1
      id: 1
      mgmt_ip: 10.100.100.4/24