---
type: media_leaf

media_leaf:
  defaults:
    platform: 720XP
    loopback_ipv4_pool: 169.27.195.0/25
    loopback_ipv4_offset: 1
    uplink_switches: [ 'blue-spine1', 'blue-spine1' ]
    max_parallel_uplinks: 2
    uplink_ipv4_pool: 100.83.100.0/23
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    bgp_defaults:
    # Literal bgp commands <str>
      - bgp asn notation asdot
      #- no bgp default ipv4-unicast
      - timers bgp 5 15
      - distance bgp 20 200 200
      - graceful-restart restart-time 300
      - graceful-restart
      - maximum-paths 128
      - neighbor default send-community
      - redistribute attached-host
    filter:
      tenants: [ blue ]
    ptp:
      source_ip: 172.31.1.12
      priority1: 30
      priority2: 103
      ttl: 8
      monitor:
        #enabled: <bool; default=True>
        threshold:
          offset_from_master: 500
          mean_path_delay: 2500
        missing_message:
                sequence_ids:
                  enabled: False
  nodes:
    - name: blue-leaf1
      id: 1
      loopback_ipv4_address: 169.27.195.34
      bgp_as: "65211.37201"
      mgmt_ip: 10.176.143.143/27
      mgmt_gateway: 10.176.143.129
      filter:
        tags: [ blue-leaf1 ]
      uplink_switches: [ 'blue-spine1', 'blue-spine1', 'blue-spine1', 'blue-spine1', 'blue-spine1', 'blue-spine1' ]
      uplink_interfaces: [ Ethernet2/1, Ethernet2/2, Ethernet2/3, Ethernet2/4, Ethernet3/1, Ethernet3/2 ]
      uplink_switch_interfaces: [ Ethernet6/18/1, Ethernet6/19/1, Ethernet6/20/1, Ethernet7/1/1,  Ethernet7/2/1, Ethernet7/3/1 ]
      # uplink_ipv4_pool: 100.83.88.0/28
      ptp:
        source_ip: 169.27.195.34

    - name: blue-leaf2
      id: 7
      loopback_ipv4_address: 169.27.195.35
      bgp_as: "65211.37202"
      mgmt_ip: 10.176.143.172/27
      mgmt_gateway: 10.176.143.129
      filter:
        tags: [ blue-leaf2 ]
      uplink_switches: [ 'blue-spine1', 'blue-spine1', 'blue-spine1', 'blue-spine1', 'blue-spine1', 'blue-spine1' ]
      uplink_interfaces: [ Ethernet2/1, Ethernet2/3, Ethernet3/1, Ethernet2/2, Ethernet2/4, Ethernet3/2 ]
      uplink_switch_interfaces: [ Ethernet6/4/1, Ethernet6/5/1, Ethernet6/6/1, Ethernet7/4/1, Ethernet7/5/1, Ethernet7/6/1 ]
      # uplink_ipv4_pool: 100.83.88.16/28
      ptp:
        source_ip: 169.27.195.35

    - name: blue-leaf3
      id: 14
      loopback_ipv4_address: 169.27.195.36
      bgp_as: "65211.37205"
      mgmt_ip: 10.166.80.7/27
      mgmt_gateway: 10.166.80.1
      filter:
        tags: [ blue-leaf3 ]
      uplink_switches: [ 'blue-spine1', 'blue-spine1' ]
      uplink_interfaces: [ Ethernet55, Ethernet56 ]
      uplink_switch_interfaces: [ Ethernet3/32/2, Ethernet4/32/2 ]
      # uplink_ipv4_pool: 100.83.88.32/28
      ptp:
        source_ip: 169.27.195.36

    - name: blue-leaf4
      id: 17
      loopback_ipv4_address: 169.27.195.37
      bgp_as: "65211.37203"
      mgmt_ip: 10.166.80.12/27
      mgmt_gateway: 10.166.80.1
      filter:
        tags: [ blue-leaf4 ]
      uplink_switches: [ 'blue-spine1', 'blue-spine1', 'blue-spine1' ]
      uplink_interfaces: [ Ethernet2/1, Ethernet2/3, Ethernet2/2 ]
      uplink_switch_interfaces: [ Ethernet6/7/1, Ethernet6/8/1, Ethernet7/7/1 ]
      # uplink_ipv4_pool: 100.83.88.48/28
      ptp:
        source_ip: 169.27.195.37

    - name: blue-leaf5
      id: 21
      loopback_ipv4_address: 169.27.195.38
      bgp_as: "65211.37206"
      mgmt_ip: 10.166.80.41/27
      mgmt_gateway: 10.166.80.33
      filter:
        tags: [ blue-leaf5 ]
      uplink_switches: [ 'blue-spine1', 'blue-spine1', 'blue-spine1', 'blue-spine1' ]
      uplink_interfaces: [ Ethernet56, Ethernet54, Ethernet55, Ethernet53 ]
      uplink_switch_interfaces: [ Ethernet3/31/4, Ethernet3/32/3, Ethernet4/32/3, Ethernet5/33/3 ]
      # uplink_ipv4_pool: 100.83.88.64/28
      ptp:
        source_ip: 169.27.195.38

    - name: blue-leaf6
      id: 26
      loopback_ipv4_address: 169.27.195.39
      bgp_as: "65211.37204"
      mgmt_ip: 10.166.80.46/27
      mgmt_gateway: 10.166.80.33
      filter:
        tags: [ blue-leaf6 ]
      uplink_switches: [ 'blue-spine1', 'blue-spine1' ]
      uplink_interfaces: [ Ethernet2/2, Ethernet2/1, Ethernet2/3 ]
      uplink_switch_interfaces: [ Ethernet6/9/1, Ethernet7/8/1, Ethernet7/9/1 ]
      # uplink_ipv4_pool: 100.83.88.80/28
      ptp:
        source_ip: 169.27.195.39

    # - name: blue-leaf7
    #   id: 12
    #   bgp_as: "65011.7"
    #   mgmt_ip: 10.100.100.11/24
    #   filter:
    #     tags: [ blue-leaf7 ]
    # - name: blue-leaf8
    #   id: 13
    #   bgp_as: "65011.8"
    #   mgmt_ip: 10.100.100.12/24
    #   filter:
    #     tags: [ blue-leaf8 ]
    # - name: blue-leaf9
    #   id: 14
    #   bgp_as: "65011.9"
    #   mgmt_ip: 10.100.100.13/24
    #   filter:
    #     tags: [ blue-leaf9 ]
    # - name: blue-leaf10
    #   id: 15
    #   bgp_as: "65011.10"
    #   mgmt_ip: 10.100.100.14/24
    #   filter:
    #     tags: [ blue-leaf10 ]
    # - name: blue-leaf11
    #   id: 16
    #   bgp_as: "65011.11"
    #   mgmt_ip: 10.100.100.15/24
    #   filter:
    #     tags: [ blue-leaf11 ]
    # - name: blue-leaf12
    #   id: 17
    #   bgp_as: "65011.12"
    #   mgmt_ip: 10.100.100.16/24
    #   filter:
    #     tags: [ blue-leaf12 ]
    # - name: blue-leaf13
    #   id: 18
    #   bgp_as: "65011.13"
    #   mgmt_ip: 10.100.100.17/24
    #   filter:
    #     tags: [ blue-leaf13 ]
    # - name: blue-leaf14
    #   id: 19
    #   bgp_as: "65011.14"
    #   mgmt_ip: 10.100.100.18/24
    #   filter:
    #     tags: [ blue-leaf14 ]
    # - name: blue-leaf15
    #   id: 20
    #   bgp_as: "65011.15"
    #   mgmt_ip: 10.100.100.19/24
    #   filter:
    #     tags: [ blue-leaf15 ]
    # - name: blue-leaf16
    #   id: 21
    #   bgp_as: "65011.16"
    #   mgmt_ip: 10.100.100.20/24
    #   filter:
    #     tags: [ blue-leaf16 ]
    # - name: blue-leaf17
    #   id: 22
    #   bgp_as: "65011.17"
    #   mgmt_ip: 10.100.100.21/24
    #   filter:
    #     tags: [ blue-leaf17 ]
    # - name: blue-leaf18
    #   id: 23
    #   bgp_as: "65011.18"
    #   mgmt_ip: 10.100.100.22/24
    #   filter:
    #     tags: [ blue-leaf18 ]
    # - name: blue-leaf19
    #   id: 24
    #   bgp_as: "65011.19"
    #   mgmt_ip: 10.100.100.23/24
    #   filter:
    #     tags: [ blue-leaf19 ]
    # - name: blue-leaf20
    #   id: 25
    #   bgp_as: "65011.20"
    #   mgmt_ip: 10.100.100.24/24
    #   filter:
    #     tags: [ blue-leaf20 ]
    # - name: blue-leaf21
    #   id: 26
    #   bgp_as: "65011.21"
    #   mgmt_ip: 10.100.100.25/24
    #   filter:
    #     tags: [ blue-leaf21 ]
    # - name: blue-leaf22
    #   id: 27
    #   bgp_as: "65011.22"
    #   mgmt_ip: 10.100.100.26/24
    #   filter:
    #     tags: [ blue-leaf22 ]
    # - name: blue-leaf23
    #   id: 28
    #   bgp_as: "65011.23"
    #   mgmt_ip: 10.100.100.27/24
    #   filter:
    #     tags: [ blue-leaf23 ]
    # - name: blue-leaf24
    #   id: 29
    #   bgp_as: "65011.24"
    #   mgmt_ip: 10.100.100.28/24
    #   filter:
    #     tags: [ blue-leaf24 ]
    # - name: blue-leaf25
    #   id: 30
    #   bgp_as: "65011.25"
    #   mgmt_ip: 10.100.100.29/24
    #   filter:
    #     tags: [ blue-leaf25 ]
    # - name: blue-leaf26
    #   id: 31
    #   bgp_as: "65011.26"
    #   mgmt_ip: 10.100.100.30/24
    #   filter:
    #     tags: [ blue-leaf26 ]
    # - name: blue-leaf27
    #   id: 32
    #   bgp_as: "65011.27"
    #   mgmt_ip: 10.100.100.31/24
    #   filter:
    #     tags: [ blue-leaf27 ]
    # - name: blue-leaf28
    #   id: 33
    #   bgp_as: "65011.28"
    #   mgmt_ip: 10.100.100.32/24
    #   filter:
    #     tags: [ blue-leaf28 ]
    # - name: blue-leaf29
    #   id: 34
    #   bgp_as: "65011.29"
    #   mgmt_ip: 10.100.100.33/24
    #   filter:
    #     tags: [ blue-leaf29 ]
    # - name: blue-leaf30
    #   id: 35
    #   bgp_as: "65011.30"
    #   mgmt_ip: 10.100.100.34/24
    #   filter:
    #     tags: [ blue-leaf30 ]
    # - name: blue-leaf31
    #   id: 36
    #   bgp_as: "65011.31"
    #   mgmt_ip: 10.100.100.35/24
    #   filter:
    #     tags: [ blue-leaf31 ]
    # - name: blue-leaf32
    #   id: 37
    #   bgp_as: "65011.32"
    #   mgmt_ip: 10.100.100.36/24
    #   filter:
    #     tags: [ blue-leaf32 ]
