---
type: media_spine

media_spine:
  defaults:
    platform: 7808R3
    loopback_ipv4_pool: 169.27.195.0/25
    bgp_as: "65010.1"
    bgp_defaults:
    # Literal bgp commands <str>
      - bgp asn notation asdot
      #- no bgp default ipv4-unicast
      - timers bgp 5 15
      - distance bgp 20 200 200
      - graceful-restart restart-time 300
      - graceful-restart
      - maximum-paths 128
      - neighbor default send-community
    filter:
      tenants: [ blue ]
    ptp:
      priority1: 20
      ttl: 8
      monitor:
        #enabled: <bool; default=True>
        threshold:
          offset_from_master: 500
          mean_path_delay: 2500
        missing_message:
                sequence_ids:
                  enabled: False
  nodes:
    - name: blue-spine1
      id: 38
      mgmt_ip: 10.100.100.4/24
      ptp:
        source_ip: loopback0
        priority2: 102
    - name: blue-spine2
      id: 39
      mgmt_ip: 10.100.100.5/24
      ptp:
        source_ip: loopback0
        priority2: 103