---
type: media_leaf

media_leaf:
  defaults:
    platform: 720XP
    loopback_ipv4_pool: 169.27.195.0/25
    loopback_ipv4_offset: 1
    uplink_switches: [ 'blue-spine1', 'blue-spine1' ]
    max_parallel_uplinks: 2
    uplink_ipv4_pool: 100.83.88.0/23
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    bgp_defaults:
    # Literal bgp commands <str>
      - bgp asn notation asdot
      - no bgp default ipv4-unicast
      - timers bgp 5 15
      - distance bgp 20 200 200
      - graceful-restart restart-time 300
      - graceful-restart
      - maximum-paths 128
      - neighbor default send-community
    filter:
      tenants: [ blue ]
    ptp:
      priority2: 2
  nodes:
    - name: blue-leaf1
      id: 6
      bgp_as: "65011.1"
      mgmt_ip: 10.100.100.5/24
      filter:
        tags: [ blue-leaf1 ]
    - name: blue-leaf2
      id: 7
      bgp_as: "65011.2"
      mgmt_ip: 10.100.100.6/24
      filter:
        tags: [ blue-leaf2 ]
    - name: blue-leaf3
      id: 8
      bgp_as: "65011.3"
      mgmt_ip: 10.100.100.7/24
      filter:
        tags: [ blue-leaf3 ]
    - name: blue-leaf4
      id: 9
      bgp_as: "65011.4"
      mgmt_ip: 10.100.100.8/24
      filter:
        tags: [ blue-leaf4 ]
    - name: blue-leaf5
      id: 10
      bgp_as: "65011.5"
      mgmt_ip: 10.100.100.9/24
      filter:
        tags: [ blue-leaf5 ]
    - name: blue-leaf6
      id: 11
      bgp_as: "65011.6"
      mgmt_ip: 10.100.100.10/24
      filter:
        tags: [ blue-leaf6 ]
    - name: blue-leaf7
      id: 12
      bgp_as: "65011.7"
      mgmt_ip: 10.100.100.11/24
      filter:
        tags: [ blue-leaf7 ]
    - name: blue-leaf8
      id: 13
      bgp_as: "65011.8"
      mgmt_ip: 10.100.100.12/24
      filter:
        tags: [ blue-leaf8 ]
    - name: blue-leaf9
      id: 14
      bgp_as: "65011.9"
      mgmt_ip: 10.100.100.13/24
      filter:
        tags: [ blue-leaf9 ]
    - name: blue-leaf10
      id: 15
      bgp_as: "65011.10"
      mgmt_ip: 10.100.100.14/24
      filter:
        tags: [ blue-leaf10 ]
    - name: blue-leaf11
      id: 16
      bgp_as: "65011.11"
      mgmt_ip: 10.100.100.15/24
      filter:
        tags: [ blue-leaf11 ]
    - name: blue-leaf12
      id: 17
      bgp_as: "65011.12"
      mgmt_ip: 10.100.100.16/24
      filter:
        tags: [ blue-leaf12 ]
    - name: blue-leaf13
      id: 18
      bgp_as: "65011.13"
      mgmt_ip: 10.100.100.17/24
      filter:
        tags: [ blue-leaf13 ]
    - name: blue-leaf14
      id: 19
      bgp_as: "65011.14"
      mgmt_ip: 10.100.100.18/24
      filter:
        tags: [ blue-leaf14 ]
    - name: blue-leaf15
      id: 20
      bgp_as: "65011.15"
      mgmt_ip: 10.100.100.19/24
      filter:
        tags: [ blue-leaf15 ]
    - name: blue-leaf16
      id: 21
      bgp_as: "65011.16"
      mgmt_ip: 10.100.100.20/24
      filter:
        tags: [ blue-leaf16 ]
    - name: blue-leaf17
      id: 22
      bgp_as: "65011.17"
      mgmt_ip: 10.100.100.21/24
      filter:
        tags: [ blue-leaf17 ]
    - name: blue-leaf18
      id: 23
      bgp_as: "65011.18"
      mgmt_ip: 10.100.100.22/24
      filter:
        tags: [ blue-leaf18 ]
    - name: blue-leaf19
      id: 24
      bgp_as: "65011.19"
      mgmt_ip: 10.100.100.23/24
      filter:
        tags: [ blue-leaf19 ]
    - name: blue-leaf20
      id: 25
      bgp_as: "65011.20"
      mgmt_ip: 10.100.100.24/24
      filter:
        tags: [ blue-leaf20 ]
    - name: blue-leaf21
      id: 26
      bgp_as: "65011.21"
      mgmt_ip: 10.100.100.25/24
      filter:
        tags: [ blue-leaf21 ]
    - name: blue-leaf22
      id: 27
      bgp_as: "65011.22"
      mgmt_ip: 10.100.100.26/24
      filter:
        tags: [ blue-leaf22 ]
    - name: blue-leaf23
      id: 28
      bgp_as: "65011.23"
      mgmt_ip: 10.100.100.27/24
      filter:
        tags: [ blue-leaf23 ]
    - name: blue-leaf24
      id: 29
      bgp_as: "65011.24"
      mgmt_ip: 10.100.100.28/24
      filter:
        tags: [ blue-leaf24 ]
    - name: blue-leaf25
      id: 30
      bgp_as: "65011.25"
      mgmt_ip: 10.100.100.29/24
      filter:
        tags: [ blue-leaf25 ]
    - name: blue-leaf26
      id: 31
      bgp_as: "65011.26"
      mgmt_ip: 10.100.100.30/24
      filter:
        tags: [ blue-leaf26 ]
    - name: blue-leaf27
      id: 32
      bgp_as: "65011.27"
      mgmt_ip: 10.100.100.31/24
      filter:
        tags: [ blue-leaf27 ]
    - name: blue-leaf28
      id: 33
      bgp_as: "65011.28"
      mgmt_ip: 10.100.100.32/24
      filter:
        tags: [ blue-leaf28 ]
    - name: blue-leaf29
      id: 34
      bgp_as: "65011.29"
      mgmt_ip: 10.100.100.33/24
      filter:
        tags: [ blue-leaf29 ]
    - name: blue-leaf30
      id: 35
      bgp_as: "65011.30"
      mgmt_ip: 10.100.100.34/24
      filter:
        tags: [ blue-leaf30 ]
    - name: blue-leaf31
      id: 36
      bgp_as: "65011.31"
      mgmt_ip: 10.100.100.35/24
      filter:
        tags: [ blue-leaf31 ]
    - name: blue-leaf32
      id: 37
      bgp_as: "65011.32"
      mgmt_ip: 10.100.100.36/24
      filter:
        tags: [ blue-leaf32 ]
