---
type: border_leaf

border_leaf:
  defaults:
    platform: 7280CR3
    loopback_ipv4_pool: 169.27.195.0/25
    uplink_switches: [ 'red-spine1', 'blue-spine1', 'green-spine1', 'green-spine2' ]
    uplink_ipv4_pool: 100.83.88.0/23
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    filter:
      tenants: [ border ]
    bgp_defaults:
    # Literal bgp commands <str>
      - bgp asn notation asdot
      #- no bgp default ipv4-unicast
      - timers bgp 5 15
      - distance bgp 20 200 200
      - graceful-restart restart-time 300
      - graceful-restart
      - maximum-paths 128
      - neighbor default send-community
    bgp_as: "65214"
    ptp:
      priority1: 20
      priority2: 101
      ttl: 8
      monitor:
        #enabled: <bool; default=True>
        threshold:
          offset_from_master: 500
          mean_path_delay: 2500
        missing_message:
                sequence_ids:
                  enabled: False

  nodes:
    - name: border-leaf1
      id: 3
      mgmt_ip: 10.100.101.4/24
      filter:
        tags: [ border-leaf1 ]
      uplink_switch_interfaces: [ Ethernet33/1, Ethernet33/1 ]
      ptp:
        source_ip: loopback0

    - name: border-leaf2
      id: 4
      mgmt_ip: 10.100.101.5/24
      filter:
        tags: [ border-leaf2 ]
      uplink_switch_interfaces: [ Ethernet34/1, Ethernet34/1 ]
      ptp:
        source_ip: loopback0
