---
type: ptp_leaf

ptp_leaf:
  defaults:
    platform: vEOS-lab
    loopback_ipv4_pool: 10.255.3.0/27
    uplink_switches: [ 'amber-spine1', 'blue-spine1' ]
    uplink_ipv4_pool: 10.255.249.0/26
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    filter:
      tenants: [ ptp ]

  nodes:
    - name: av-bl-1
      id: 3
      bgp_as: "65450"
      mgmt_ip: 172.16.3.101/24
      filter:
        tags: [ av-bl-1 ]
      uplink_switch_interfaces:
        - Ethernet7
        - Ethernet7

    - name: av-bl-2
      id: 4
      bgp_as: "65450"
      mgmt_ip: 172.16.3.102/24
      filter:
        tags: [ av-bl-2 ]
      uplink_switch_interfaces:
        - Ethernet8
        - Ethernet8
