---
type: border_leaf

border_leaf:
  defaults:
    platform: 7280CR3
    loopback_ipv4_pool: 169.27.195.0/25
    uplink_switches: [ 'red-spine1', 'blue-spine1', 'green-spine1', 'green-spine2' ]
    uplink_ipv4_pool: 100.83.88.0/23
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    filter:
      tenants: [ border ]
    ptp:
      priority1: 20
      priority2: 101
      ttl: 8
      monitor:
        #enabled: <bool; default=True>
        threshold:
          offset_from_master: 500
          mean_path_delay: 2500
        missing_message:
                sequence_ids:
                  enabled: False

  nodes:
    - name: border-leaf1
      id: 3
      bgp_as: "65003.2"
      mgmt_ip: 10.100.101.4/24
      filter:
        tags: [ border-leaf1 ]
      uplink_switch_interfaces: [ Ethernet33/1, Ethernet33/1 ]
      ptp:
        source_ip: loopback0

    - name: border-leaf2
      id: 4
      bgp_as: "65003.2"
      mgmt_ip: 10.100.101.5/24
      filter:
        tags: [ border-leaf2 ]
      uplink_switch_interfaces: [ Ethernet34/1, Ethernet34/1 ]
      ptp:
        source_ip: loopback0


core_interfaces:
  p2p_links:
    - ip: [ 100.83.88.249//31, 100.83.88.248/31 ]
      nodes: [ border-leaf1, green-spine1 ]
      interfaces: [ Ethernet35/1, Ethernet3/3/1 ]
      include_in_underlay_protocol: true
      # If the AS is different than the AS number configured for the node,
      # the local-as will be replaced on this BGP peering (neighbor <ip> local-as <as> no-prepend replace-as).
      as: [ "65003.2", "65003.3"  ]
    - ip: [ 100.83.88.251/31, 100.83.88.250/31 ]
      nodes: [ border-leaf1, green-spine2 ]
      interfaces: [ Ethernet36/1 , Ethernet3/3/1 ]
      include_in_underlay_protocol: true
      # If the AS is different than the AS number configured for the node,
      # the local-as will be replaced on this BGP peering (neighbor <ip> local-as <as> no-prepend replace-as).
      as: [ "65003.2", "65003.3" ]
    - ip: [ 100.83.88.253/31, 100.83.88.252/31 ]
      nodes: [ border-leaf2 , green-spine1 ]
      interfaces: [ Ethernet35/1, Ethernet3/4/1 ]
      include_in_underlay_protocol: true
      # If the AS is different than the AS number configured for the node,
      # the local-as will be replaced on this BGP peering (neighbor <ip> local-as <as> no-prepend replace-as).
      as: [ "65003.2", "65003.3" ]
    - ip: [ 100.83.88.255/31, 100.83.88.254/31 ]
      nodes: [ border-leaf2, green-spine2 ]
      interfaces: [ Ethernet36/1, Ethernet3/4/1 ]
      include_in_underlay_protocol: true
      # If the AS is different than the AS number configured for the node,
      # the local-as will be replaced on this BGP peering (neighbor <ip> local-as <as> no-prepend replace-as).
      as: [ "65003.2", "65003.3" ]
