---
type: border_leaf

border_leaf:
  defaults:
    platform: 7280CR3
    loopback_ipv4_pool: 169.27.195.0/25
    uplink_switches: [ 'red-spine1', 'blue-spine1', 'green-spine1', 'green-spine2' ]
    uplink_ipv4_pool: 100.83.88.0/23
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    filter:
      tenants: [ border ]

  nodes:
    - name: border-leaf1
      id: 3
      bgp_as: "65003.2"
      mgmt_ip: 10.100.101.4/24
      filter:
        tags: [ border-leaf1 ]
      uplink_switch_interfaces: [ Ethernet33/1, Ethernet33/1 ]

    - name: border-leaf2
      id: 4
      bgp_as: "65003.2"
      mgmt_ip: 10.100.101.5/24
      filter:
        tags: [ border-leaf2 ]
      uplink_switch_interfaces: [ Ethernet34/1, Ethernet34/1 ]
