---
# Port Profiles
# Common settings inherited to network_ports
port_profiles:

  # To intoduce multicast ipv4 static
  - profile: STATIC_MULTICAST
    structured_config:
      multicast:
        ipv4:
          static: True
  - profile: RED_111
    mode: access
    enabled: false
    vlans: "111"
    spanning_tree_portfast: edge
    spanning_tree_bpdufilter: enabled
    ptp:
      enabled: true
    structured_config:
      multicast:
        ipv4:
          static: True
  - profile: RED_112
    mode: access
    enabled: false
    vlans: "112"
    spanning_tree_portfast: edge
    spanning_tree_bpdufilter: enabled
    ptp:
      enabled: true
    structured_config:
      multicast:
        ipv4:
          static: True
  - profile: BLUE_211
    mode: access
    enabled: false
    vlans: "211"
    spanning_tree_portfast: edge
    spanning_tree_bpdufilter: enabled
    ptp:
      enabled: true
    structured_config:
      multicast:
        ipv4:
          static: True
  - profile: BLUE_212
    mode: access
    enabled: false
    vlans: "212"
    spanning_tree_portfast: edge
    spanning_tree_bpdufilter: enabled
    ptp:
      enabled: true
    structured_config:
      multicast:
        ipv4:
          static: True

# Network Ports
# All switch_ports ranges are expanded into individual port configurations
# Switches are matched with regex matching the full hostname.
network_ports:
  # Static muuticast for Red/Blue spines all interfaces except uplinks to PTP & BL
  - switches:
    # All 7280SR3 Media leafs ports 1-48 and 49-56/1
    - C160064-004B101A
    # - C160064-006B101A
    # - C160064-008B101A
    # - C160064-010B101A
    # - C160064-013B101A
    # - C160064-014B101A
    # - C160064-014B102A
    # - C160064-015B103A
    # - C160064-015B102A
    # - C160064-015B101A
    # - C160064-017B101A
    # - C160064-037B106A
    # - C160064-037B105A
    # - C160064-046B101A
    # - C160064-051B101A
    # - C160064-056B101A
    # - C160064-004B201A
    # - C160064-006B201A
    # - C160064-008B201A
    # - C160064-010B201A
    # - C160064-013B201A
    # - C160064-014B201A
    # - C160064-014B202A
    # - C160064-015B203A
    # - C160064-015B202A
    # - C160064-015B201A
    # - C160064-017B201A
    # - C160064-037B206A
    # - C160064-037B205A
    # - C160064-046B201A
    # - C160064-051B201A
    # - C160064-056B201A
    switch_ports:
      - Ethernet1-48
      - Ethernet49-56/1

      # - Ethernet3-4/1-31/1
      # - Ethernet3-4/32-36/1
      # - Ethernet5/1-36/1
      # - Ethernet6-7/1-24/1
      # - Ethernet6-7/26-36/1
    profile: STATIC_MULTICAST

  # Generic Port Settings
  - switches:
      - red-leaf1
    switch_ports:
      - Ethernet3-48
    profile: RED_111
    description: RED_VLAN111

  - switches:
      - red-leaf2
    switch_ports:
      - Ethernet3-48
    profile: RED_112
    description: RED_VLAN112

  - switches:
      - blue-leaf1
    switch_ports:
      - Ethernet3-48
    profile: BLUE_211
    description: BLUE_VLAN211

  - switches:
      - blue-leaf2
    switch_ports:
      - Ethernet3-48
    profile: BLUE_212
    description: BLUE_VLAN212

  # media-PTP-1
  - switches:
      - media-PTP-1
    switch_ports:
      - Ethernet6-48
    enabled: false
    description: Routed Endpoints
    speed: forced 1000full
    # structured_config:
    #   type: routed

  - switches:
      - media-PTP-1
    switch_ports:
      - Ethernet5
    enabled: true
    description: PTP Grandmaster 1
    speed: forced 1000full
    mode: access
    vlans: 131
    ptp:
      enabled: true
      endpoint_role: bmca

  # media-PTP-2
  - switches:
      - media-PTP-2
    switch_ports:
      - Ethernet6-48
    enabled: false
    description: Routed Endpoints
    speed: forced 1000full
    # structured_config:
    #   type: routed

  - switches:
      - media-PTP-2
    switch_ports:
      - Ethernet5
    enabled: true
    description: PTP Grandmaster 2
    speed: forced 1000full
    mode: access
    vlans: 132
    ptp:
      enabled: true
      endpoint_role: bmca
