fabric_name: FABRIC

node_type_keys:
  - key: ptp_leaf
    type: ptp_leaf
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
  - key: border_leaf
    type: border_leaf
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
    default_ptp_priority1: 30
  - key: media_spine
    type: media_spine
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
    default_ptp_priority1: 20
  - key: media_leaf
    type: media_leaf
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
    default_ptp_priority1: 30

# local users
local_users:
  - name: admin
    privilege: 15
    role: network-admin
    sha512_password: "$6$eucN5ngreuExDgwS$xnD7T8jO..GBDX0DUlp.hn.W7yW94xTjSanqgaQGBzPIhDAsyAl9N4oScHvOMvf07uVBFI4mKMxwdVEUVKgY/."
  - name: avnetuser
    privilege: 0
    role: network-user
    sha512_password: "$6$l7sHbz6mxuq6peq0$FQjHbRIfcZrdI1Cw7Qs4HhUbFbzmUa.dTleGY95TgzEJgNvHh/TlhzCClknEk634p5nQHn/RFBEjebebU4jxd."
  - name: providius
    privilege: 7
    role: network-operator
    sha512_password: "$6$BQgcQzmXutC8.k0U$w5Ly4dFtFe9KUYOc6XmPSnm0cW3F/uL90jfA1EkfH16TI4n5PcSWNk7byu1LSUR8i8ha0dWFrMHkX9b76Ih6X1"
  - name: testlab
    privilege: 15
    role: network-admin
    sha512_password: "$6$emh7YIY16uJLWXGR$rpNN3L9JAe6K2eynKi6lcoSUQFm7Uxa6gCRwEOA8FO7adXHv31Xd4PFwybBe3icIsxGHZjQvjEKocceIiMXIc/"
  - name: thelabeng
    privilege: 15
    role: network-admin
    sha512_password: "$6$/D8cGV410nyAUOxm$TvYHuvz9sK3.EWQeT6EiNHVclEa3EOjgYZ6022WCekli1LVLzUHql27CnUV6/NlHL0Mn9qtj8yRL6w58hFSHS0"
  - name: ansible
    privilege: 15
    role: network-admin
    sha512_password: $6$7u4j1rkb3VELgcZE/TapRoci0XaIZsL4tFzgq1YZBLD9c6f/knXzvcYY0NcMKndZeCv0T268knGKhOEwZAxqKjlMm920


logging:
  # Console logging severity level.
  monitor: "notifications"

mcs_client:
  shutdown: false

bgp_peer_groups:
  ipv4_underlay_peers:
    name: P2P-IPv4-eBGP-PEERS
    password: tAFzZuVu4+b6rGq1btvPBg==

p2p_uplinks_mtu: 1500

default_interfaces:
  - types:
      - media_spine
    platforms:
      - 7808R3
    uplink_interfaces:
      - Ethernet3/1-4/1
    downlink_interfaces:
      - Ethernet4-7/1-36/1
  - types:
      - media_leaf
    platforms:
      - 7289R3A
      - 7280SR3
    uplink_interfaces:
      - Ethernet4-10/1-16/1
      - Ethernet49-56/1
    downlink_interfaces:
      - Ethernet1-48
      - Ethernet1-48
  - types:
      - ptp_leaf
    platforms:
      - 7280SR3
    uplink_interfaces:
      - Ethernet49-56/1
    downlink_interfaces:
      - Ethernet1-48
  - types:
      - border_leaf
    platforms:
      - 7280CR3
    uplink_interfaces:
      - Ethernet1-36/1-4

daemon_terminattr:
  cvaddrs:
    - 192.168.1.12:9910
  cvauth:
    method: token
    token_file: /tmp/token
  cvvrf: MGMT
  disable_aaa: true
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  taillogs:

# Changed ptp to ptp_settings
ptp_settings:
  enabled: true
  auto_clock_identity: false
  domain: 100

spanning_tree:
  mode: "mstp"

snmp_server:
  communities:
      # Community name.
    - name: gt1m3rg3r
      access: "ro"
  local_interfaces:
      # Interface name.
    - name: loopback0
  hosts:
    - host: 202.40.72.61
      community: gt1m3rg3r
      version: "2c"
    - host: 202.40.73.61
      community: gt1m3rg3r
      version: "2c"

hardware:
  speed_groups:
    - speed_group: 4
      # Serdes speed like "10g" or "25g".
      serdes: "10g"
system:
  l1:
    unsupported_speed_action: "error"
    unsupported_error_correction_action: "error"
clock:
  timezone: America/New_York

management_api_http:
  enable_http: True
  enable_https: False

# management_cvx:
#   shutdown: false
#   server_hosts:
#   # IP or hostname.
#     - 172.16.131.127
#     - 172.16.131.128
#     - 172.16.131.129
#   # Interface name.
#   source_interface: Loopback0

management_api_gnmi:
  provider: "eos-native"
  transport:
    grpc:
        # Transport name.
      - name: NRVT
        vrf: MGMT
        port: 5909

management_api_models:
  providers:
    - name: "smash"
      paths:
        - path: bridging
        - path: ptp
        - path: routing
  # providers:
  #   - name: "macsec"

management_ssh:
  access_groups:
      # Standard ACL Name.
    - name: MGMT-SSH-ACL
      # VRF Name.
      vrf: MGMT

standard_access_lists:
    # Access-list Name.
  - name: MGMT-SSH-ACL
    counters_per_entry: False
    sequence_numbers: # required
        # Sequence ID.
      - sequence: 10
        # Action as string.
        # Example: "deny ip any any"
        action: permit host 172.20.111.100

ip_http_client_source_interfaces:
    # Interface Name.
  - name: Management 1
    vrf: MGMT

# Enable pim sparse mode on L3 uplinks
underlay_multicast: False

# Enable multicast routing
router_multicast:
  ipv4:
    routing: True

aaa_authentication:
  login:
    default: local
aaa_authorization:
  exec:
    default: local

mgmt_interface: Management1
mgmt_gateway: 10.100.100.1
mgmt_destination_networks:
  - 0.0.0.0/0


name_servers:
  - 192.168.1.1


# ntp:
#   local_interface:
#     name: Management1
#     vrf: MGMT
#   servers:
#     - name: 0.pool.ntp.org
#       vrf: MGMT

ntp:
  servers:
    # IP or hostname e.g., 2.2.2.55, 2001:db8::55, ie.pool.ntp.org.
    - name: 172.16.131.2
      burst: False
      iburst: True
      preferred: False
      # VRF name.
      vrf: MGMT
    - name: 172.16.131.3
      burst: False
      iburst: True
      preferred: True
      # VRF name.
      vrf: MGMT
roles:
    # Role name.
  - name: network-user
    sequence_numbers:
        # Sequence number.
      - sequence: 10
        action: "deny"
        # "config", "config-all", "exec" or mode key as string.
        mode: "exec"
        # Command as string.
        command: enable|configure|bash|python-shell|\|
      - sequence: 20
        action: "permit"
        # "config", "config-all", "exec" or mode key as string.
        mode: "exec"
        # Command as string.
        command: ".*"


# Create UPLINKS -> Media Spines to BL and PTP, -> Green Spines to BL and PTP (Note: Green spines are used here just to configure PTP/BL for them )
#

core_interfaces:
  p2p_links:

    #++++++ Border Leaf to Border Leaf Switch L3 Interlinks without Port-Channel
    - ip: [ 100.83.93.8/31, 100.83.93.9/31 ]
      nodes: [ C160064-037B380A, C160064-037B381A ]
      include_in_underlay_protocol: true
      interfaces: [ Ethernet35/1, Ethernet35/1 ]
      as: [ "65214", "65214" ]

    - ip: [ 100.83.93.10/31, 100.83.93.11/31 ]
      nodes: [ C160064-037B380A, C160064-037B381A ]
      include_in_underlay_protocol: true
      interfaces: [ Ethernet36/1, Ethernet36/1 ]
      as: [ "65214", "65214" ]

    #+++++++++ PTP Switch L3 Interlinks without Port-Channel
    - ip: [ 100.83.93.12/31, 100.83.93.13/31 ]
      nodes: [ C160064-037B370A, C160064-037B371A ]
      include_in_underlay_protocol: true
      interfaces: [ Ethernet53/1, Ethernet53/1 ]
      as: [ "65213.37370", "65213.37370" ]

    - ip: [ 100.83.93.14/31, 100.83.93.15/31 ]
      nodes: [ C160064-037B370A, C160064-037B371A ]
      include_in_underlay_protocol: true
      interfaces: [ Ethernet54/1, Ethernet54/1 ]
      as: [ "65213.37370", "65213.37370" ]


    #+++++++ Border to Green Spines p2p L3 Links
    - ip: [ 100.83.93.17/31, 100.83.93.16/31 ]
      nodes: [ C160064-037B380A, C160064-037B300A  ]
      interfaces: [ Ethernet31/1, Ethernet3/30/1 ]
      include_in_underlay_protocol: true
      # If the AS is different than the AS number configured for the node,
      # the local-as will be replaced on this BGP peering (neighbor <ip> local-as <as> no-prepend replace-as).
      as: [ "65214", "65212.37300" ]

    - ip: [ 100.83.93.19/31, 100.83.93.18/31 ]
      nodes: [ C160064-037B380A, C160064-037B301A ]
      interfaces: [ Ethernet32/1, Ethernet3/30/1 ]
      include_in_underlay_protocol: true
      # If the AS is different than the AS number configured for the node,
      # the local-as will be replaced on this BGP peering (neighbor <ip> local-as <as> no-prepend replace-as).
      as: [ "65214", "65212.37300" ]

    - ip: [ 100.83.93.21/31, 100.83.93.20/31 ]
      nodes: [ C160064-037B381A, C160064-037B300A  ]
      interfaces: [ Ethernet31/1, Ethernet4/30/1 ]
      include_in_underlay_protocol: true
      # If the AS is different than the AS number configured for the node,
      # the local-as will be replaced on this BGP peering (neighbor <ip> local-as <as> no-prepend replace-as).
      as: [ "65214", "65212.37300" ]

    - ip: [ 100.83.93.23/31, 100.83.93.22/31 ]
      nodes: [ C160064-037B381A, C160064-037B301A ]
      interfaces: [ Ethernet32/1, Ethernet4/30/1 ]
      include_in_underlay_protocol: true
      # If the AS is different than the AS number configured for the node,
      # the local-as will be replaced on this BGP peering (neighbor <ip> local-as <as> no-prepend replace-as).
      as: [ "65214", "65212.37300" ]

    #+++++ PTP to Green Spines p2p L3 Links
    - ip: [ 100.83.93.25/31, 100.83.93.24/31 ]
      nodes: [ C160064-037B370A, C160064-037B300A  ]
      interfaces: [ Ethernet51/1, Ethernet3/31/1 ]
      include_in_underlay_protocol: true
      # If the AS is different than the AS number configured for the node,
      # the local-as will be replaced on this BGP peering (neighbor <ip> local-as <as> no-prepend replace-as).
      as: [ "65003.37370", "65212.37300" ]

    - ip: [ 100.83.93.27/31, 100.83.93.26/31 ]
      nodes: [ C160064-037B370A, C160064-037B301A ]
      interfaces: [ Ethernet52/1, Ethernet3/31/1 ]
      include_in_underlay_protocol: true
      # If the AS is different than the AS number configured for the node,
      # the local-as will be replaced on this BGP peering (neighbor <ip> local-as <as> no-prepend replace-as).
      as: [ "65003.37370", "65212.37300" ]

    - ip: [ 100.83.93.29/31, 100.83.93.28/31 ]
      nodes: [ C160064-037B371A, C160064-037B300A  ]
      interfaces: [ Ethernet51/1, Ethernet4/31/1 ]
      include_in_underlay_protocol: true
      # If the AS is different than the AS number configured for the node,
      # the local-as will be replaced on this BGP peering (neighbor <ip> local-as <as> no-prepend replace-as).
      as: [ "65003.37370", "65212.37300" ]

    - ip: [ 100.83.93.31/31, 100.83.93.30/31 ]
      nodes: [ C160064-037B371A, C160064-037B301A ]
      interfaces: [ Ethernet52/1, Ethernet4/31/1 ]
      include_in_underlay_protocol: true
      # If the AS is different than the AS number configured for the node,
      # the local-as will be replaced on this BGP peering (neighbor <ip> local-as <as> no-prepend replace-as).
      as: [ "65003.37370", "65212.37300" ]



eos_validate_state_validation_mode_loose: true
root_dir: '{{ inventory_dir }}'
eos_validate_state_name: 'reports'
eos_validate_state_dir: '{{ root_dir }}/{{ eos_validate_state_name }}'
eos_validate_state_md_report_path: '{{ eos_validate_state_dir }}/{{ fabric_name }}-state.md'
eos_validate_state_csv_report_path: '{{ eos_validate_state_dir }}/{{ fabric_name }}-state.csv'
validate_state_markdown_flavor: "default"
accepted_xcvr_manufacturers: "{{ validation_role.xcvr_own_manufacturers | arista.avd.default(['Arastra, Inc.', 'Arista Networks']) }}"
accepted_pwr_supply_states: "{{ validation_role.pwr_supply_states | arista.avd.default(['ok']) }}"
accepted_fan_states: "{{ validation_role.fan_states | arista.avd.default(['ok']) }}"
validation_report_md: "{{ validation_role.validation_report_md | arista.avd.default(true) }}"
