---
type: ptp_leaf

ptp_leaf:
  defaults:
    platform: 7280SR3
    loopback_ipv4_pool: 169.27.195.0/25
    uplink_switches: [ 'red-spine1', 'blue-spine1', 'green-spine1', 'green-spine2' ]
    uplink_ipv4_pool: 100.83.88.0/23
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    filter:
      tenants: [ ptp ]
    bgp_defaults:
    # Literal bgp commands <str>
      - bgp asn notation asdot
      #- no bgp default ipv4-unicast
      - timers bgp 5 15
      - distance bgp 20 200 200
      - graceful-restart restart-time 300
      - graceful-restart
      - maximum-paths 128
      - neighbor default send-community
    bgp_as: "65213.37370"
    ptp:
      # source_ip: 172.31.200.12
      priority1: 10
      # priority2: 100
      ttl: 8
      monitor:
        #enabled: <bool; default=True>
        threshold:
          offset_from_master: 500
          mean_path_delay: 2500
        missing_message:
                sequence_ids:
                  enabled: False

  nodes:
    - name: media-PTP-1
      id: 1
      loopback_ipv4_address: 169.27.195.72
      mgmt_ip: 10.176.143.137/27
      mgmt_gateway: 10.176.143.129
      filter:
        tags: [ media-PTP-1 ]
      uplink_switch_interfaces:
        - Ethernet3/32/1
        - Ethernet3/32/1
      ptp:
        source_ip: 169.27.195.72
        priority2: 101

    - name: media-PTP-2
      id: 2
      loopback_ipv4_address: 169.27.195.73
      mgmt_ip: 10.176.143.167/27
      mgmt_gateway: 10.176.143.161
      filter:
        tags: [ media-PTP-2 ]
      uplink_switch_interfaces:
        - Ethernet4/32/1
        - Ethernet4/32/1
      ptp:
        source_ip: 169.27.195.73
        priority2: 102
