---
type: ptp_leaf

ptp_leaf:
  defaults:
    platform: 7280SR3
    loopback_ipv4_pool: 169.27.195.0/25
    uplink_switches: [ 'C160064-037B100A', 'C160064-037B200A', 'C160064-037B300A', 'C160064-037B301A' ]
    uplink_ipv4_pool: 100.83.93.0/24
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    filter:
      tenants: [ ptp ]
    bgp_as: "65213.37370"
    bgp_defaults:
    # Literal bgp commands <str>
      - bgp asn notation asdot
      - timers bgp 5 15
      - neighbor default send-community
      #- maximum-paths 128
      #- no bgp default ipv4-unicast
      # - distance bgp 20 200 200
      # - graceful-restart restart-time 300
      # - graceful-restart
      #- no redistribute attached-host
    ptp:
      priority1: 10
      #priority2: 103
      ttl: 8
      monitor:
        #enabled: <bool; default=True>
        threshold:
          offset_from_master: 500
          mean_path_delay: 2500
        missing_message:
                sequence_ids:
                  enabled: False

  nodes:
    - name: C160064-037B370A
      id: 3
      loopback_ipv4_address: 169.27.195.72
      mgmt_interface: Management1
      mgmt_ip: 10.176.143.137/27
      mgmt_gateway: 10.176.143.129
      filter:
        tags: [ C160064-037B370A ]
      uplink_switches: [ 'C160064-037B100A', 'C160064-037B200A' ]
      uplink_interfaces: [ Ethernet33/1, Ethernet34/1 ]
      uplink_switch_interfaces: [ Ethernet9/12/1, Ethernet9/13/1 ]
      # uplink_switch_interfaces:
      #   - Ethernet49-56/1
      #   - Ethernet1-48
      ptp:
        priority2: 101

    - name: C160064-037B371A
      id: 4
      loopback_ipv4_address: 169.27.195.73
      mgmt_interface: Management1
      mgmt_ip: 10.176.143.166/27
      mgmt_gateway: 10.176.143.161
      filter:
        tags: [ C160064-037B371A ]
      uplink_switches: [ 'C160064-037B100A', 'C160064-037B200A' ]
      uplink_interfaces: [ Ethernet33/1, Ethernet34/1 ]
      uplink_switch_interfaces: [ Ethernet9/13/1, Ethernet9/14/1 ]
      # uplink_switch_interfaces:
      #   - Ethernet49-56/1
      #   - Ethernet1-48
      ptp:
        priority2: 102
