---
type: ptp_leaf

ptp_leaf:
  defaults:
    platform: 7280SR3
    loopback_ipv4_pool: 169.27.195.0/25
    uplink_switches: [ 'red-spine1', 'blue-spine1', 'green-spine1', 'green-spine2' ]
    uplink_ipv4_pool: 100.83.88.0/23
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    filter:
      tenants: [ ptp ]
    ptp:
      # source_ip: 172.31.200.12
      priority1: 10
      # priority2: 100
      ttl: 8
      monitor:
        #enabled: <bool; default=True>
        threshold:
          offset_from_master: 500
          mean_path_delay: 2500
        missing_message:
                sequence_ids:
                  enabled: False

  nodes:
    - name: media-PTP-1
      id: 1
      bgp_as: "65003.1"
      mgmt_ip: 10.100.101.2/24
      filter:
        tags: [ media-PTP-1 ]
      uplink_switch_interfaces:
        - Ethernet49/1
        - Ethernet49/1
      ptp:
        source_ip: loopback0
        priority2: 101

    - name: media-PTP-2
      id: 2
      bgp_as: "65003.1"
      mgmt_ip: 10.100.100.3/24
      filter:
        tags: [ media-PTP-2 ]
      uplink_switch_interfaces:
        - Ethernet50/1
        - Ethernet50/1
      ptp:
        source_ip: loopback0
        priority2: 102

