---
# inventory.yml
DC1:
  children:
    CLOUDVISION:
      hosts:
        cvp:
          # Ansible variables used by the ansible_avd and ansible_cvp roles to push configuration to devices via CVP
          ansible_host: 192.168.1.12
          ansible_user: ansible
          ansible_password: ansible
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false
          ansible_network_os: eos
    FABRIC:
      children:
        DC1_SPINES:
          hosts:
            SPINE1:
              ansible_host: 172.16.100.101
            SPINE2:
              ansible_host: 172.16.100.102
        DC1_LEAFS:
          hosts:
            LEAF1A:
              ansible_host: 172.16.100.103
            LEAF1B:
              ansible_host: 172.16.100.104
            LEAF2A:
              ansible_host: 172.16.100.105
            LEAF3A:
              ansible_host: 172.16.100.106
            LEAF3B:
              ansible_host: 172.16.100.107
            LEAF3C:
              ansible_host: 172.16.100.108
            LEAF3D:
              ansible_host: 172.16.100.109
            LEAF3E:
              ansible_host: 172.16.100.110
    DC1_NETWORK_SERVICES:
      children:
        DC1_LEAFS:
        DC1_SPINES:
    DC1_NETWORK_PORTS:
      children:
        DC1_LEAFS:
        DC1_SPINES:
