---
all:
  children:
    CLOUDVISION:
      hosts:
        cvp:
          # Ansible variables used by the ansible_avd and ansible_cvp roles to push configuration to devices via CVP
          ansible_host: 192.168.1.12
          ansible_user: ansible
          ansible_password: ansible
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false
          ansible_network_os: eos
    FABRIC:
      children:
        RED:
          children:
            RED_SPINES:
              hosts:
                C160064-037B100A:
                  description: red-spine1
                  serial_number: HNN23076021
                  ansible_host: 10.176.143.139/27
            RED_LEAFS:
              hosts:
                C160064-037B101A:
                  description: red-leaf1
                  serial_number: JPA2423A0HM
                  ansible_host: 10.176.143.141/27
                C160064-037B102A:
                  description: red-leaf2
                  serial_number: JPA2403A1WC
                  ansible_host: 10.176.143.170/27
                C160064-037B105A:
                  description: red-leaf3
                  serial_number: JPA2416P3JC
                  ansible_host: 10.166.80.6/27
                C160064-037B103A:
                  description: red-leaf4
                  serial_number: JPA2401A3GM
                  ansible_host: 10.166.80.10/27
                C160064-037B106A:
                  description: red-leaf5
                  serial_number: JPA2416P1VH
                  ansible_host: 10.166.80.40/27
                C160064-037B104A:
                  description: red-leaf6
                  serial_number: JPA2401A3W6
                  ansible_host: 10.166.80.44/27
                C160064-001B101A:
                  description: red-leaf7
                  serial_number: NA
                  ansible_host: 10.176.142.83/28
                C160064-002B101A:
                  description: red-leaf8
                  serial_number: NA
                  ansible_host: 10.176.142.102/28
                C160064-003B101A:
                  description: red-leaf9
                  serial_number: NA
                  ansible_host: 10.176.136.154/28
                C160064-004B101A:
                  description: red-leaf10
                  serial_number: NA
                  ansible_host: 10.176.136.185/28
                C160064-005B101A:
                  description: red-leaf11
                  serial_number: NA
                  ansible_host: 10.176.136.218/28
                C160064-006B101A:
                  description: red-leaf12
                  serial_number: NA
                  ansible_host: 10.176.136.250/28
                C160064-007B101A:
                  description: red-leaf13
                  serial_number: NA
                  ansible_host: 10.176.137.26/28
                C160064-008B101A:
                  description: red-leaf14
                  serial_number: NA
                  ansible_host: 10.176.137.58/28
                C160064-009B101A:
                  description: red-leaf15
                  serial_number: NA
                  ansible_host: 10.176.137.90/28
                C160064-010B101A:
                  description: red-leaf16
                  serial_number: NA
                  ansible_host: 10.176.137.122/28
                C160064-013B101A:
                  description: red-leaf17
                  serial_number: NA
                  ansible_host: 10.176.142.116/28
                C160064-013B102A:
                  description: red-leaf18
                  serial_number: NA
                  ansible_host: 10.176.142.133/28
                C160064-014B101A:
                  description: red-leaf19
                  serial_number: NA
                  ansible_host: 10.176.142.148/28
                C160064-014B102A:
                  description: red-leaf20
                  serial_number: NA
                  ansible_host: 10.176.142.164/28
                C160064-015B101A:
                  description: red-leaf21
                  serial_number: NA
                  ansible_host: 10.176.142.187/28
                C160064-015B102A:
                  description: red-leaf22
                  serial_number: NA
                  ansible_host: 10.176.142.189/28
                C160064-015B103A:
                  description: red-leaf23
                  serial_number: NA
                  ansible_host: 10.176.142.191/28
                C160064-016B101A:
                  description: red-leaf24
                  serial_number: NA
                  ansible_host: 10.176.142.215/28
                C160064-016B102A:
                  description: red-leaf25
                  serial_number: NA
                  ansible_host: 10.176.142.231/28
                C160064-017B101A:
                  description: red-leaf26
                  serial_number: NA
                  ansible_host: 10.176.142.248/28
                C160064-046B101A:
                  description: red-leaf27
                  serial_number: NA
                  ansible_host: 10.176.141.119/28
                C160064-049B101A:
                  description: red-leaf28
                  serial_number: NA
                  ansible_host: 10.176.141.167/28
                C160064-050B101A:
                  description: red-leaf29
                  serial_number: NA
                  ansible_host: 10.176.143.86/28
                C160064-051B101A:
                  description: red-leaf30
                  serial_number: NA
                  ansible_host: 10.176.143.100/28
                C160064-051B102A:
                  description: red-leaf31
                  serial_number: NA
                  ansible_host: 10.176.143.118/28
                C160064-056B101A:
                  description: red-leaf32
                  serial_number: NA
                  ansible_host: 10.176.142.21/28
            BLUE_SPINES:
              hosts:
                C160064-037B200A:
                  description: blue-spine1
                  serial_number: NA
                  ansible_host: 10.176.143.168/27
            BLUE_LEAFS:
              hosts:

                C160064-037B201A:
                  description: blue-leaf1
                  serial_number: JPA2423A0HG
                  ansible_host: 10.176.143.143/27
                C160064-037B202A:
                  description: blue-leaf2
                  serial_number: JPA2401A3W3
                  ansible_host: 10.176.143.172/27
                C160064-037B205A:
                  description: blue-leaf3
                  serial_number: JPA2416P3K9
                  ansible_host: 10.166.80.7/27
                C160064-037B203A:
                  description: blue-leaf4
                  serial_number: JPA2402A092
                  ansible_host: 10.166.80.12/27
                C160064-037B206A:
                  description: blue-leaf5
                  serial_number: JPA2416P3GF
                  ansible_host: 10.166.80.41/27
                C160064-037B204A:
                  description: blue-leaf6
                  serial_number: JPA2401A3W5
                  ansible_host: 10.166.80.46/27
                C160064-001B201A:
                  description: blue-leaf7
                  serial_number: NA
                  ansible_host: 10.176.142.84/28
                C160064-002B201A:
                  description: blue-leaf8
                  serial_number: NA
                  ansible_host: 10.176.142.103/28
                C160064-003B201A:
                  description: blue-leaf9
                  serial_number: NA
                  ansible_host: 10.176.136.155/28
                C160064-004B201A:
                  description: blue-leaf10
                  serial_number: NA
                  ansible_host: 10.176.136.186/28
                C160064-005B201A:
                  description: blue-leaf11
                  serial_number: NA
                  ansible_host: 10.176.136.219/28
                C160064-006B201A:
                  description: blue-leaf12
                  serial_number: NA
                  ansible_host: 10.176.136.251/28
                C160064-007B201A:
                  description: blue-leaf13
                  serial_number: NA
                  ansible_host: 10.176.137.27/28
                C160064-008B201A:
                  description: blue-leaf14
                  serial_number: NA
                  ansible_host: 10.176.137.59/28
                C160064-009B201A:
                  description: blue-leaf15
                  serial_number: NA
                  ansible_host: 10.176.137.91/28
                C160064-010B201A:
                  description: blue-leaf16
                  serial_number: NA
                  ansible_host: 10.176.137.123/28
                C160064-013B201A:
                  description: blue-leaf17
                  serial_number: NA
                  ansible_host: 10.176.142.117/28
                C160064-013B202A:
                  description: blue-leaf18
                  serial_number: NA
                  ansible_host: 10.176.142.134/28
                C160064-014B201A:
                  description: blue-leaf19
                  serial_number: NA
                  ansible_host: 10.176.142.149/28
                C160064-014B202A:
                  description: blue-leaf20
                  serial_number: NA
                  ansible_host: 10.176.142.165/28
                C160064-015B201A:
                  description: blue-leaf21
                  serial_number: NA
                  ansible_host: 10.176.142.188/28
                C160064-015B202A:
                  description: blue-leaf22
                  serial_number: NA
                  ansible_host: 10.176.142.190/28
                C160064-015B203A:
                  description: blue-leaf23
                  serial_number: NA
                  ansible_host: 10.176.142.192/28
                C160064-016B201A:
                  description: blue-leaf24
                  serial_number: NA
                  ansible_host: 10.176.142.216/28
                C160064-016B202A:
                  description: blue-leaf25
                  serial_number: NA
                  ansible_host: 10.176.142.232/28
                C160064-017B201A:
                  description: blue-leaf26
                  serial_number: NA
                  ansible_host: 10.176.142.249/28
                C160064-046B201A:
                  description: blue-leaf27
                  serial_number: NA
                  ansible_host: 10.176.141.120/28
                C160064-049B201A:
                  description: blue-leaf28
                  serial_number: NA
                  ansible_host: 10.176.141.168/28
                C160064-050B201A:
                  description: blue-leaf29
                  serial_number: NA
                  ansible_host: 10.176.143.87/28
                C160064-051B201A:
                  description: blue-leaf30
                  serial_number: NA
                  ansible_host: 10.176.143.101/28
                C160064-051B202A:
                  description: blue-leaf31
                  serial_number: NA
                  ansible_host: 10.176.143.119/28
                C160064-056B201A:
                  description: blue-leaf32
                  serial_number: NA
                  ansible_host: 10.176.142.22/28
        PTP_LEAFS:
          hosts:
            C160064-037B370A:
                  description: ptp-1
                  serial_number: JPA2416P3HN
                  ansible_host: 10.176.143.137/27
            C160064-037B371A:
                  description: ptp-2
                  serial_number: JPA2416P3JA
                  ansible_host: 10.176.143.166/27
        BORDER_LEAFS:
          hosts:
              C160064-037B380A:
                  description: border-leaf1
                  serial_number: JPA2409P23Z
                  ansible_host: 10.176.143.138/27
              C160064-037B381A:
                  description: border-leaf2
                  serial_number: JPA2409P250
                  ansible_host: 10.176.143.167/27
    NETWORK_SERVICES:
      children:
        RED_LEAFS:
        BLUE_LEAFS:
        PTP_LEAFS:
        BORDER_LEAFS:
    CONNECTED_ENDPOINTS:
      children:
        RED_SPINES:
        BLUE_SPINES:
        RED_LEAFS:
        BLUE_LEAFS:
        PTP_LEAFS:
        BORDER_LEAFS:
