---
### group_vars/DC1.yml

# local users
local_users:
  - name: admin
    privilege: 15
    role: network-admin
    sha512_password: "$6$eucN5ngreuExDgwS$xnD7T8jO..GBDX0DUlp.hn.W7yW94xTjSanqgaQGBzPIhDAsyAl9N4oScHvOMvf07uVBFI4mKMxwdVEUVKgY/."

# AAA Authorization
aaa_authorization:
  exec:
    default: local

# OOB Management network default gateway.
mgmt_gateway: 172.16.100.1
mgmt_interface: Management0

# dns servers.
name_servers:
  - 8.8.4.4
  - 8.8.8.8

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp_settings:
  server_vrf: use_mgmt_interface_vrf
  servers:
    - name: time.google.com
    - name: pool.ntp.org

standard_access_lists:
    # Access-list Name.
  - name: MGMT-SSH-ACL
    counters_per_entry: False
    sequence_numbers: # required
        # Sequence ID.
      - sequence: 10
        # Action as string.
        # Example: "deny ip any any"
        action: permit host 172.20.111.100
